# Generated by Django 3.0.5 on 2020-05-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insurance_name', models.CharField(max_length=100)),
                ('Insurance_img', models.ImageField(upload_to='pics')),
                ('Insurance_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Primary_insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ispolicy', models.CharField(max_length=100)),
                ('customer_name', models.TextField()),
                ('mobile', models.IntegerField()),
                ('reg_no', models.TextField()),
                ('company_name', models.TextField()),
                ('model_name', models.TextField()),
                ('reg_in', models.TextField()),
                ('reg_date', models.DateField()),
                ('policy_status', models.TextField()),
                ('expiry_date', models.DateField()),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
